hack
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

diff --git a/.github/actions/publish-prime-image/action.yml b/.github/actions/publish-prime-image/action.yml
--- a/.github/actions/publish-prime-image/action.yml
+++ b/.github/actions/publish-prime-image/action.yml
@@ -49,10 +49,10 @@ runs:
         IMAGE: ${{ inputs.image }}
         REGISTRY: ${{ inputs.registry }}
       run: |
-        if [[ "$REGISTRY" == docker.io ]]; then
-          echo "The prime or staging registry cannot be docker.io" >&2
-          exit 1
-        fi
+        # if [[ "$REGISTRY" == docker.io ]]; then
+        #   echo "The prime or staging registry cannot be docker.io" >&2
+        #   exit 1
+        # fi
 
         cache_scope="${CACHE_SCOPE:-$IMAGE}"
         cache_scope="${cache_scope//[^a-zA-Z0-9_.-]/-}"
